version: "3.8"
services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:80"
  depends_on:
   - sqldata
  environment:
    ConnectionStrings__MotocomplexConnectionString: "Server=sqldata;Database=MotocomplexDb;User Id=sa;Password=Motocomplex@;TrustServerCertificate=True"
 sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Motocomplex@