version: "3.8"
services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:80"
  depends_on:
   - sqldata
  environment:
    ConnectionStrings__MotocomplexConnectionString: "Server=localhost\\mssqllocaldb;Database=MotocomplexDb;User Id=Motocomplex;Password=Motocomplex@;"
 sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Motocomplex@
      - MSSQL_SA_USER=Motocomplex
    ports:
      - "5434:1433"
      
