version: "3.8"
services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:80"
  depends_on:
   - db
 db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      ConnectionStrings__MotocomplexConnectionString: "Server=(localdb)\\mssqllocaldb;Database=MotocomplexDb;Trusted_Connection=True;"
    ports:
      - "3306:3306"
      
